sonar.projectKey=Jochem-tb_SOA3_Solo
sonar.projectName=AvansDevOps
sonar.sources=.
sonar.exclusions=**/bin/**,**/obj/**,.git/**,.github/**

sonar.modules=AvansDevOps.Domain,AvansDevOps.Infrastructure,AvansDevOps.Tests

AvansDevOps.Domain.sonar.projectBaseDir=./AvansDevOps.Domain
AvansDevOps.Domain.sonar.projectKey=Jochem-tb_SOA3_Solo:AvansDevOps.Domain
AvansDevOps.Domain.sonar.sources=.

AvansDevOps.Infrastructure.sonar.projectBaseDir=./AvansDevOps.Infrastructure
AvansDevOps.Infrastructure.sonar.projectKey=Jochem-tb_SOA3_Solo:AvansDevOps.Infrastructure
AvansDevOps.Infrastructure.sonar.sources=.

AvansDevOps.Tests.sonar.projectBaseDir=./AvansDevOps.Tests
AvansDevOps.Tests.sonar.projectKey=Jochem-tb_SOA3_Solo:AvansDevOps.Tests
AvansDevOps.Tests.sonar.sources=.
